/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen1p2_jazminsalgado;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author evaja
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        tp_menuadmin.setVisible(false);
        tp_menuUser.setVisible(false);
        bt_Salir.setVisible(false);
        lb_saldo.setVisible(false);
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        lb_saldo.setText("Saldo de usuario: " + saldo);

        modelo = (DefaultComboBoxModel) cb_tiporef.getModel();
        modelo.addElement("diccionario");
        modelo.addElement("enciclopedia");
        modelo.addElement("manual");
        modelo.addElement("tecnico");
        modelo.addElement("tesauro");
        cb_tiporef.setModel(modelo);

        modelo = new DefaultComboBoxModel();
        modelo = (DefaultComboBoxModel) cb_tipoFic.getModel();
        modelo.addElement("novela");
        modelo.addElement("scifi");
        modelo.addElement("misterio");
        modelo.addElement("adventura");
        cb_tipoFic.setModel(modelo);

        modelo = new DefaultComboBoxModel();
        modelo = (DefaultComboBoxModel) cb_tiponofic.getModel();
        modelo.addElement("ensayo");
        modelo.addElement("biografia");
        modelo.addElement("autobiografia");
        modelo.addElement("revista cientifica");
        cb_tiponofic.setModel(modelo);

        modelo = new DefaultComboBoxModel();

        modelo = (DefaultComboBoxModel) cb_listar.getModel();
        modelo.addElement("Todos");
        modelo.addElement("Libro de Texto");
        modelo.addElement("Libro de referencias");
        modelo.addElement("Libro de Ficcion");
        modelo.addElement("Libro de No Ficcion");
        cb_listar.setModel(modelo);
        modelo = new DefaultComboBoxModel();

        modelo = (DefaultComboBoxModel) cb_tipo.getModel();
        modelo.addElement("Libro de Texto");
        modelo.addElement("Libro de referencias");
        modelo.addElement("Libro de Ficcion");
        modelo.addElement("Libro de No Ficcion");
        cb_tipo.setModel(modelo);
        cb_tipoeliminar.setModel(modelo);
        cb_tipocompra.setModel(modelo);
        cb_tipodevuelve.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_Salir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_adminuser = new javax.swing.JTextField();
        pf_adminpswd = new javax.swing.JPasswordField();
        bt_loginAdmin = new javax.swing.JButton();
        bt_usuariologin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tp_menuadmin = new javax.swing.JTabbedPane();
        pn_publicar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_titulo = new javax.swing.JTextField();
        tf_autor = new javax.swing.JTextField();
        tf_precio = new javax.swing.JTextField();
        bt_publicar = new javax.swing.JButton();
        tp_modelos = new javax.swing.JTabbedPane();
        pn_librotexto = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_curso = new javax.swing.JTextField();
        tf_facultad = new javax.swing.JTextField();
        pn_libroref = new javax.swing.JPanel();
        cb_tiporef = new javax.swing.JComboBox<>();
        pn_librofic = new javax.swing.JPanel();
        cb_tipoFic = new javax.swing.JComboBox<>();
        pn_libronofic = new javax.swing.JPanel();
        cb_tiponofic = new javax.swing.JComboBox<>();
        pn_listarlibros = new javax.swing.JPanel();
        cb_listar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_listar = new javax.swing.JTextArea();
        pn_editar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_tituloeditar = new javax.swing.JTextField();
        tf_autoreditar = new javax.swing.JTextField();
        tf_precioeditar = new javax.swing.JTextField();
        bt_editar = new javax.swing.JButton();
        cb_tipo = new javax.swing.JComboBox<>();
        cb_libro = new javax.swing.JComboBox<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        tb_editar = new javax.swing.JTable();
        pn_eliminar = new javax.swing.JPanel();
        cb_tipoeliminar = new javax.swing.JComboBox<>();
        cb_libroeliminar = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_eliminar = new javax.swing.JTextArea();
        bt_eliminar = new javax.swing.JButton();
        lb_saldo = new javax.swing.JLabel();
        tp_menuUser = new javax.swing.JTabbedPane();
        pn_comprar = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_compra = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_transaccion = new javax.swing.JTextArea();
        bt_comprar = new javax.swing.JButton();
        cb_tipocompra = new javax.swing.JComboBox<>();
        cb_librocompra = new javax.swing.JComboBox<>();
        pn_devolver = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_devolver = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        ta_reembolzo = new javax.swing.JTextArea();
        bt_devolver = new javax.swing.JButton();
        cb_tipodevuelve = new javax.swing.JComboBox<>();
        cb_librodevuele = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_Salir.setText("Salir");
        bt_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_SalirMouseClicked(evt);
            }
        });

        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrador Log In\n");
        login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 144, 311, 74));

        tf_adminuser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        login.add(tf_adminuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 210, 180, 32));

        pf_adminpswd.setText("jPasswordField1");
        pf_adminpswd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pf_adminpswdMouseClicked(evt);
            }
        });
        login.add(pf_adminpswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 252, 150, 37));

        bt_loginAdmin.setText("Log in Administrador");
        bt_loginAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_loginAdminMouseClicked(evt);
            }
        });
        login.add(bt_loginAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 190, 30));

        bt_usuariologin.setText("Ingresar como usuario");
        bt_usuariologin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_usuariologinMouseClicked(evt);
            }
        });
        login.add(bt_usuariologin, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 465, 197, 38));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre de Usuario");
        login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 198, -1, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña");
        login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 251, -1, 40));

        jLabel4.setText("Titulo: ");

        jLabel5.setText("Autor: ");

        jLabel6.setText("Precio:");

        bt_publicar.setText("publicar Libro");
        bt_publicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_publicarMouseClicked(evt);
            }
        });

        jLabel7.setText("Facultad: ");

        jLabel8.setText("Curso: ");

        javax.swing.GroupLayout pn_librotextoLayout = new javax.swing.GroupLayout(pn_librotexto);
        pn_librotexto.setLayout(pn_librotextoLayout);
        pn_librotextoLayout.setHorizontalGroup(
            pn_librotextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_librotextoLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(pn_librotextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pn_librotextoLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_facultad, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_librotextoLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(tf_curso, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        pn_librotextoLayout.setVerticalGroup(
            pn_librotextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_librotextoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pn_librotextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_facultad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_librotextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_curso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        tp_modelos.addTab("Libro de Texto", pn_librotexto);

        javax.swing.GroupLayout pn_librorefLayout = new javax.swing.GroupLayout(pn_libroref);
        pn_libroref.setLayout(pn_librorefLayout);
        pn_librorefLayout.setHorizontalGroup(
            pn_librorefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_librorefLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(cb_tiporef, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        pn_librorefLayout.setVerticalGroup(
            pn_librorefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_librorefLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(cb_tiporef, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        tp_modelos.addTab("Libro de referencia", pn_libroref);

        javax.swing.GroupLayout pn_libroficLayout = new javax.swing.GroupLayout(pn_librofic);
        pn_librofic.setLayout(pn_libroficLayout);
        pn_libroficLayout.setHorizontalGroup(
            pn_libroficLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_libroficLayout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(cb_tipoFic, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        pn_libroficLayout.setVerticalGroup(
            pn_libroficLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_libroficLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(cb_tipoFic, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        tp_modelos.addTab("Libro de Ficcion", pn_librofic);

        javax.swing.GroupLayout pn_libronoficLayout = new javax.swing.GroupLayout(pn_libronofic);
        pn_libronofic.setLayout(pn_libronoficLayout);
        pn_libronoficLayout.setHorizontalGroup(
            pn_libronoficLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_libronoficLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(cb_tiponofic, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        pn_libronoficLayout.setVerticalGroup(
            pn_libronoficLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_libronoficLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(cb_tiponofic, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        tp_modelos.addTab("Libro de No ficcion", pn_libronofic);

        javax.swing.GroupLayout pn_publicarLayout = new javax.swing.GroupLayout(pn_publicar);
        pn_publicar.setLayout(pn_publicarLayout);
        pn_publicarLayout.setHorizontalGroup(
            pn_publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_publicarLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(pn_publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pn_publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_publicarLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addContainerGap(374, Short.MAX_VALUE))
            .addGroup(pn_publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_publicarLayout.createSequentialGroup()
                    .addComponent(tp_modelos)
                    .addContainerGap()))
            .addGroup(pn_publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_publicarLayout.createSequentialGroup()
                    .addGap(177, 177, 177)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(502, Short.MAX_VALUE)))
            .addGroup(pn_publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_publicarLayout.createSequentialGroup()
                    .addGap(173, 173, 173)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(492, Short.MAX_VALUE)))
            .addGroup(pn_publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_publicarLayout.createSequentialGroup()
                    .addContainerGap(650, Short.MAX_VALUE)
                    .addComponent(bt_publicar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        pn_publicarLayout.setVerticalGroup(
            pn_publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_publicarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pn_publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(440, Short.MAX_VALUE))
            .addGroup(pn_publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_publicarLayout.createSequentialGroup()
                    .addContainerGap(375, Short.MAX_VALUE)
                    .addComponent(tp_modelos, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(66, 66, 66)))
            .addGroup(pn_publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_publicarLayout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(499, Short.MAX_VALUE)))
            .addGroup(pn_publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_publicarLayout.createSequentialGroup()
                    .addGap(132, 132, 132)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(443, Short.MAX_VALUE)))
            .addGroup(pn_publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_publicarLayout.createSequentialGroup()
                    .addContainerGap(585, Short.MAX_VALUE)
                    .addComponent(bt_publicar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        tp_menuadmin.addTab("Publicar Libro", pn_publicar);

        cb_listar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_listarItemStateChanged(evt);
            }
        });

        ta_listar.setColumns(20);
        ta_listar.setRows(5);
        jScrollPane1.setViewportView(ta_listar);

        javax.swing.GroupLayout pn_listarlibrosLayout = new javax.swing.GroupLayout(pn_listarlibros);
        pn_listarlibros.setLayout(pn_listarlibrosLayout);
        pn_listarlibrosLayout.setHorizontalGroup(
            pn_listarlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_listarlibrosLayout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(cb_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
            .addGroup(pn_listarlibrosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pn_listarlibrosLayout.setVerticalGroup(
            pn_listarlibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_listarlibrosLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(cb_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        tp_menuadmin.addTab("Listar Libros", pn_listarlibros);

        pn_editar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Tipo:");
        pn_editar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 30, 96, 39));

        jLabel10.setText("Libro:");
        pn_editar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 75, 96, 39));

        jLabel11.setText("Titulo: ");
        pn_editar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 132, 96, 39));

        jLabel12.setText("Autor: ");
        pn_editar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 177, 96, 39));

        jLabel13.setText("Precio: ");
        pn_editar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 222, 96, 39));
        pn_editar.add(tf_tituloeditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 140, 181, -1));
        pn_editar.add(tf_autoreditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 177, 181, -1));
        pn_editar.add(tf_precioeditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 222, 181, -1));

        bt_editar.setText("Editar Libro");
        bt_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_editarMouseClicked(evt);
            }
        });
        pn_editar.add(bt_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 440, -1, -1));

        cb_tipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tipoItemStateChanged(evt);
            }
        });
        pn_editar.add(cb_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 38, 132, -1));

        cb_libro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_libroItemStateChanged(evt);
            }
        });
        pn_editar.add(cb_libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 83, 132, -1));

        tb_editar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autor", "Precio", "Edicion"
            }
        ));
        jScrollPane9.setViewportView(tb_editar);

        pn_editar.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 300, 290));

        tp_menuadmin.addTab("Editar Libros", pn_editar);

        cb_tipoeliminar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tipoeliminarItemStateChanged(evt);
            }
        });

        cb_libroeliminar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_libroeliminarItemStateChanged(evt);
            }
        });

        jLabel14.setText("Tipo:");

        jLabel15.setText("Libro:");

        ta_eliminar.setColumns(20);
        ta_eliminar.setRows(5);
        jScrollPane3.setViewportView(ta_eliminar);

        bt_eliminar.setText("Eliminar Libro");
        bt_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_eliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_eliminarLayout = new javax.swing.GroupLayout(pn_eliminar);
        pn_eliminar.setLayout(pn_eliminarLayout);
        pn_eliminarLayout.setHorizontalGroup(
            pn_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_eliminarLayout.createSequentialGroup()
                .addGroup(pn_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_eliminarLayout.createSequentialGroup()
                        .addGroup(pn_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_eliminarLayout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addGroup(pn_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pn_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_libroeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_tipoeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pn_eliminarLayout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 300, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_eliminarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_eliminar)))
                .addContainerGap())
        );
        pn_eliminarLayout.setVerticalGroup(
            pn_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_eliminarLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pn_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_tipoeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_libroeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_eliminar)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        tp_menuadmin.addTab("Eliminar Libros", pn_eliminar);

        lb_saldo.setText("Saldo del usuario: ");

        ta_compra.setColumns(20);
        ta_compra.setRows(5);
        jScrollPane4.setViewportView(ta_compra);

        jLabel16.setText("Tipo:");

        jLabel17.setText("Libro: ");

        jLabel19.setText("Transaccion: ");

        ta_transaccion.setColumns(20);
        ta_transaccion.setRows(5);
        jScrollPane5.setViewportView(ta_transaccion);

        bt_comprar.setText("Comprar Libro");
        bt_comprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_comprarMouseClicked(evt);
            }
        });

        cb_tipocompra.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tipocompraItemStateChanged(evt);
            }
        });

        cb_librocompra.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_librocompraItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pn_comprarLayout = new javax.swing.GroupLayout(pn_comprar);
        pn_comprar.setLayout(pn_comprarLayout);
        pn_comprarLayout.setHorizontalGroup(
            pn_comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_comprarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pn_comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_comprarLayout.createSequentialGroup()
                        .addGroup(pn_comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pn_comprarLayout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116))
                            .addGroup(pn_comprarLayout.createSequentialGroup()
                                .addGroup(pn_comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pn_comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_librocompra, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_tipocompra, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28)
                        .addComponent(bt_comprar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        pn_comprarLayout.setVerticalGroup(
            pn_comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_comprarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pn_comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_comprarLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17))
                    .addGroup(pn_comprarLayout.createSequentialGroup()
                        .addComponent(cb_tipocompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_librocompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(88, 88, 88)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(bt_comprar)
                .addGap(12, 12, 12))
            .addGroup(pn_comprarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tp_menuUser.addTab("Comprar Libro", pn_comprar);

        ta_devolver.setColumns(20);
        ta_devolver.setRows(5);
        jScrollPane6.setViewportView(ta_devolver);

        jLabel20.setText("Tipo:");

        jLabel21.setText("Libro: ");

        jLabel23.setText("Transaccion: ");

        ta_reembolzo.setColumns(20);
        ta_reembolzo.setRows(5);
        jScrollPane7.setViewportView(ta_reembolzo);

        bt_devolver.setText("Devolver Libro");
        bt_devolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_devolverMouseClicked(evt);
            }
        });

        cb_tipodevuelve.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tipodevuelveItemStateChanged(evt);
            }
        });

        cb_librodevuele.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_librodevueleItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pn_devolverLayout = new javax.swing.GroupLayout(pn_devolver);
        pn_devolver.setLayout(pn_devolverLayout);
        pn_devolverLayout.setHorizontalGroup(
            pn_devolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_devolverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pn_devolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pn_devolverLayout.createSequentialGroup()
                        .addGroup(pn_devolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pn_devolverLayout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_devolverLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pn_devolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_devolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_librodevuele, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_tipodevuelve, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(bt_devolver, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        pn_devolverLayout.setVerticalGroup(
            pn_devolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_devolverLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pn_devolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cb_tipodevuelve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_devolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cb_librodevuele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(bt_devolver)
                .addGap(12, 12, 12))
            .addGroup(pn_devolverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tp_menuUser.addTab("Devolver Libro", pn_devolver);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(335, Short.MAX_VALUE)
                .addComponent(lb_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tp_menuadmin)
                    .addContainerGap()))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tp_menuUser)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(580, Short.MAX_VALUE)
                .addComponent(lb_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tp_menuadmin)
                    .addContainerGap()))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tp_menuUser)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(bt_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(712, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(606, Short.MAX_VALUE)
                .addComponent(bt_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void pf_adminpswdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pf_adminpswdMouseClicked
        pf_adminpswd.setText("");
    }//GEN-LAST:event_pf_adminpswdMouseClicked

    private void bt_loginAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginAdminMouseClicked
        String usuario = tf_adminuser.getText();
        String contraseña = pf_adminpswd.getText();

        if (contraseña.equalsIgnoreCase(pswrd) && usuario.equalsIgnoreCase(user)) {
            JOptionPane.showMessageDialog(this, "Bienvenido " + usuario);
            login.setVisible(false);
            tp_menuadmin.setVisible(true);
            bt_Salir.setVisible(true);
            tp_menuUser.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Credenciales incorrectas");
            tf_adminuser.setText("");
            pf_adminpswd.setText("");

        }
    }//GEN-LAST:event_bt_loginAdminMouseClicked

    private void bt_usuariologinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_usuariologinMouseClicked
        tp_menuUser.setVisible(true);
        login.setVisible(false);
        bt_Salir.setVisible(true);
        tp_menuadmin.setVisible(false);
        lb_saldo.setVisible(true);
    }//GEN-LAST:event_bt_usuariologinMouseClicked

    private void cb_listarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_listarItemStateChanged
        String print = "";
        if (evt.getStateChange() == 2) {
            if (cb_listar.getSelectedItem().toString().equalsIgnoreCase("Todos")) {
                for (libro libro1 : libros) {
                    if (libro1 instanceof libro) {
                        print += libro1;
                    }

                }
            } else if (cb_listar.getSelectedItem().toString().equalsIgnoreCase("Libro de Texto")) {
                for (libro libro1 : libros) {
                    if (libro1 instanceof libro_texto) {
                        print += libro1;
                    }
                }
            } else if (cb_listar.getSelectedItem().toString().equalsIgnoreCase("Libro de referencias")) {
                for (libro libro1 : libros) {
                    if (libro1 instanceof libro_referencia) {
                        print += libro1;
                    }
                }
            } else if (cb_listar.getSelectedItem().toString().equalsIgnoreCase("Libro de Ficcion")) {
                for (libro libro1 : libros) {
                    if (libro1 instanceof libro_ficcion) {
                        print += libro1;
                    }
                }
            } else if (cb_listar.getSelectedItem().toString().equalsIgnoreCase("Libro de No Ficcion")) {
                for (libro libro1 : libros) {
                    if (libro1 instanceof libro_noficcion) {
                        print += libro1;
                    }
                }
            }
            ta_listar.setText(print + "\n");
        }

    }//GEN-LAST:event_cb_listarItemStateChanged

    private void bt_publicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_publicarMouseClicked
        String title = tf_titulo.getText(),
                author = tf_autor.getText();
        double price = Double.parseDouble(tf_precio.getText());
        if (pn_librotexto.isShowing()) {
            String curso = tf_curso.getText(), facultad = tf_facultad.getText();

            libros.add(new libro_texto(curso, facultad, title, author, price, 1));
        } else if (pn_libroref.isShowing()) {
            String reftype = cb_tiporef.getSelectedItem().toString();
            libros.add(new libro_referencia(reftype, title, author, price, 1));
        } else if (pn_librofic.isShowing()) {
            String fictype = cb_tipoFic.getSelectedItem().toString();
            libros.add(new libro_ficcion(fictype, title, author, price, 1));
        } else if (pn_libronofic.isShowing()) {
            String nofictype = cb_tiponofic.getSelectedItem().toString();
            libros.add(new libro_ficcion(nofictype, title, author, price, 1));
        }

        JOptionPane.showMessageDialog(this, "Libro agregado exitosamente");
        tf_titulo.setText("");
        tf_autor.setText("");
        tf_precio.setText("");
        tf_curso.setText("");
        tf_facultad.setText("");

    }//GEN-LAST:event_bt_publicarMouseClicked

    private void bt_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_SalirMouseClicked
        bt_Salir.setVisible(false);
        login.setVisible(true);
        tp_menuadmin.setVisible(false);
        tp_menuUser.setVisible(false);
    }//GEN-LAST:event_bt_SalirMouseClicked

    private void cb_tipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tipoItemStateChanged
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo = (DefaultComboBoxModel) cb_libro.getModel();
        if (evt.getStateChange() == 2) {
            if (cb_tipo.getSelectedItem().toString().equalsIgnoreCase("Libro de Texto")) {
                modelo = new DefaultComboBoxModel();
                for (libro libro1 : libros) {
                    if (libro1 instanceof libro_texto) {

                        modelo.addElement(libro1.getTitulo() + "\n");
                    }
                }

            } else if (cb_tipo.getSelectedItem().toString().equalsIgnoreCase("Libro de referencias")) {
                modelo = new DefaultComboBoxModel();
                for (libro libro1 : libros) {
                    if (libro1 instanceof libro_referencia) {

                        modelo.addElement(libro1.getTitulo() + "\n");
                    }
                }
            } else if (cb_tipo.getSelectedItem().toString().equalsIgnoreCase("Libro de Ficcion")) {
                modelo = new DefaultComboBoxModel();
                for (libro libro1 : libros) {
                    if (libro1 instanceof libro_ficcion) {

                        modelo.addElement(libro1.getTitulo() + "\n");
                    }
                }
            } else if (cb_tipo.getSelectedItem().toString().equalsIgnoreCase("Libro de No Ficcion")) {
                modelo = new DefaultComboBoxModel();
                for (libro libro1 : libros) {
                    if (libro1 instanceof libro_noficcion) {

                        modelo.addElement(libro1.getTitulo() + "\n");
                    }
                }
            }
            cb_libro.setModel(modelo);
        }
    }//GEN-LAST:event_cb_tipoItemStateChanged

    private void cb_libroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_libroItemStateChanged
        DefaultTableModel modelo = (DefaultTableModel) tb_editar.getModel();
        if (evt.getStateChange() == 2) {
            modelo.setRowCount(0);
            if (cb_libro.getSelectedItem() instanceof libro_texto) {
                libro_texto books = (libro_texto) cb_libro.getSelectedItem();
                Object[] row = {books.getTitulo(), books.getAutor(), books.precio, books.getEdicion()};
                modelo.addRow(row);

            } else if (cb_libro.getSelectedItem() instanceof libro_referencia) {
                libro_referencia books = (libro_referencia) cb_libro.getSelectedItem();
                Object[] row = {books.getTitulo(), books.getAutor(), books.precio, books.getEdicion()};
                modelo.addRow(row);
            } else if (cb_libro.getSelectedItem() instanceof libro_ficcion) {
                libro_ficcion books = (libro_ficcion) cb_libro.getSelectedItem();
                Object[] row = {books.getTitulo(), books.getAutor(), books.precio, books.getEdicion()};
                modelo.addRow(row);
            } else if (cb_libro.getSelectedItem() instanceof libro_noficcion) {
                libro_noficcion books = (libro_noficcion) cb_libro.getSelectedItem();
                Object[] row = {books.getTitulo(), books.getAutor(), books.precio, books.getEdicion()};
                modelo.addRow(row);
            }

        }
        tb_editar.setModel(modelo);

    }//GEN-LAST:event_cb_libroItemStateChanged

    private void cb_tipoeliminarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tipoeliminarItemStateChanged
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo = (DefaultComboBoxModel) cb_libro.getModel();
        if (evt.getStateChange() == 2) {
            if (cb_tipoeliminar.getSelectedItem().toString().equalsIgnoreCase("Libro de Texto")) {
                modelo = new DefaultComboBoxModel();
                for (libro libro1 : libros) {
                    if (libro1 instanceof libro_texto) {

                        modelo.addElement(libro1.getTitulo() + "\n");
                    }
                }

            } else if (cb_tipoeliminar.getSelectedItem().toString().equalsIgnoreCase("Libro de referencias")) {
                modelo = new DefaultComboBoxModel();
                for (libro libro1 : libros) {
                    if (libro1 instanceof libro_referencia) {

                        modelo.addElement(libro1.getTitulo() + "\n");
                    }
                }
            } else if (cb_tipoeliminar.getSelectedItem().toString().equalsIgnoreCase("Libro de Ficcion")) {
                modelo = new DefaultComboBoxModel();
                for (libro libro1 : libros) {
                    if (libro1 instanceof libro_ficcion) {

                        modelo.addElement(libro1.getTitulo() + "\n");
                    }
                }
            } else if (cb_tipoeliminar.getSelectedItem().toString().equalsIgnoreCase("Libro de No Ficcion")) {
                modelo = new DefaultComboBoxModel();
                for (libro libro1 : libros) {
                    if (libro1 instanceof libro_noficcion) {

                        modelo.addElement(libro1.getTitulo() + "\n");
                    }
                }
            }
            cb_libroeliminar.setModel(modelo);
        }
    }//GEN-LAST:event_cb_tipoeliminarItemStateChanged

    private void cb_tipocompraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tipocompraItemStateChanged
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo = (DefaultComboBoxModel) cb_libro.getModel();
        if (evt.getStateChange() == 2) {
            if (cb_tipocompra.getSelectedItem().toString().equalsIgnoreCase("Libro de Texto")) {
                modelo = new DefaultComboBoxModel();
                for (libro libro1 : libros) {
                    if (libro1 instanceof libro_texto) {

                        modelo.addElement(libro1.getTitulo() + "\n");
                    }
                }

            } else if (cb_tipocompra.getSelectedItem().toString().equalsIgnoreCase("Libro de referencias")) {
                modelo = new DefaultComboBoxModel();
                for (libro libro1 : libros) {
                    if (libro1 instanceof libro_referencia) {

                        modelo.addElement(libro1.getTitulo() + "\n");
                    }
                }
            } else if (cb_tipocompra.getSelectedItem().toString().equalsIgnoreCase("Libro de Ficcion")) {
                modelo = new DefaultComboBoxModel();
                for (libro libro1 : libros) {
                    if (libro1 instanceof libro_ficcion) {

                        modelo.addElement(libro1.getTitulo() + "\n");
                    }
                }
            } else if (cb_tipocompra.getSelectedItem().toString().equalsIgnoreCase("Libro de No Ficcion")) {
                modelo = new DefaultComboBoxModel();
                for (libro libro1 : libros) {
                    if (libro1 instanceof libro_noficcion) {

                        modelo.addElement(libro1.getTitulo() + "\n");
                    }
                }
            }
            cb_librocompra.setModel(modelo);
        }
    }//GEN-LAST:event_cb_tipocompraItemStateChanged

    private void cb_tipodevuelveItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tipodevuelveItemStateChanged
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo = (DefaultComboBoxModel) cb_libro.getModel();
        if (evt.getStateChange() == 2) {
            if (cb_tipodevuelve.getSelectedItem().toString().equalsIgnoreCase("Libro de Texto")) {
                modelo = new DefaultComboBoxModel();
                for (libro libro1 : libros) {
                    if (libro1 instanceof libro_texto) {

                        modelo.addElement(libro1.getTitulo() + "\n");
                    }
                }

            } else if (cb_tipodevuelve.getSelectedItem().toString().equalsIgnoreCase("Libro de referencias")) {
                modelo = new DefaultComboBoxModel();
                for (libro libro1 : libros) {
                    if (libro1 instanceof libro_referencia) {

                        modelo.addElement(libro1.getTitulo() + "\n");
                    }
                }
            } else if (cb_tipodevuelve.getSelectedItem().toString().equalsIgnoreCase("Libro de Ficcion")) {
                modelo = new DefaultComboBoxModel();
                for (libro libro1 : libros) {
                    if (libro1 instanceof libro_ficcion) {

                        modelo.addElement(libro1.getTitulo() + "\n");
                    }
                }
            } else if (cb_tipodevuelve.getSelectedItem().toString().equalsIgnoreCase("Libro de No Ficcion")) {
                modelo = new DefaultComboBoxModel();
                for (libro libro1 : libros) {
                    if (libro1 instanceof libro_noficcion) {

                        modelo.addElement(libro1.getTitulo() + "\n");
                    }
                }
            }
            cb_librodevuele.setModel(modelo);
        }
    }//GEN-LAST:event_cb_tipodevuelveItemStateChanged

    private void bt_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_editarMouseClicked
        Object seleccion = cb_libro.getSelectedItem();
        if (seleccion != null) {
            if (seleccion instanceof libro_texto) {

                ((libro_texto) libros.get(cb_libro.getSelectedIndex())).setTitulo(tf_tituloeditar.getText());
                ((libro_texto) libros.get(cb_libro.getSelectedIndex())).setAutor(tf_autor.getText());
                ((libro_texto) libros.get(cb_libro.getSelectedIndex())).setPrecio(Double.parseDouble(tf_precioeditar.getText()));
                ((libro_texto) libros.get(cb_libro.getSelectedIndex())).setEdicion(((libro_texto) libros.get(cb_libro.getSelectedIndex())).getEdicion() + 1);

            } else if (seleccion instanceof libro_referencia) {

                ((libro_referencia) libros.get(cb_libro.getSelectedIndex())).setTitulo(tf_tituloeditar.getText());
                ((libro_referencia) libros.get(cb_libro.getSelectedIndex())).setAutor(tf_autor.getText());
                ((libro_referencia) libros.get(cb_libro.getSelectedIndex())).setPrecio(Double.parseDouble(tf_precioeditar.getText()));
                ((libro_referencia) libros.get(cb_libro.getSelectedIndex())).setEdicion(((libro_texto) libros.get(cb_libro.getSelectedIndex())).getEdicion() + 1);
            } else if (seleccion instanceof libro_ficcion) {
//             
                ((libro_ficcion) libros.get(cb_libro.getSelectedIndex())).setTitulo(tf_tituloeditar.getText());
                ((libro_ficcion) libros.get(cb_libro.getSelectedIndex())).setAutor(tf_autor.getText());
                ((libro_ficcion) libros.get(cb_libro.getSelectedIndex())).setPrecio(Double.parseDouble(tf_precioeditar.getText()));
                ((libro_ficcion) libros.get(cb_libro.getSelectedIndex())).setEdicion(((libro_texto) libros.get(cb_libro.getSelectedIndex())).getEdicion() + 1);

            } else if (seleccion instanceof libro_noficcion) {

                ((libro_noficcion) libros.get(cb_libro.getSelectedIndex())).setTitulo(tf_tituloeditar.getText());
                ((libro_noficcion) libros.get(cb_libro.getSelectedIndex())).setAutor(tf_autor.getText());
                ((libro_noficcion) libros.get(cb_libro.getSelectedIndex())).setPrecio(Double.parseDouble(tf_precioeditar.getText()));
                ((libro_noficcion) libros.get(cb_libro.getSelectedIndex())).setEdicion(((libro_texto) libros.get(cb_libro.getSelectedIndex())).getEdicion() + 1);

            }
        }
        JOptionPane.showMessageDialog(this, "Producto Modificado correctamente");
        tf_precioeditar.setText("");
        tf_tituloeditar.setText("");
        tf_autoreditar.setText("");
    }//GEN-LAST:event_bt_editarMouseClicked

    private void bt_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_eliminarMouseClicked
        Object seleccion = cb_libro.getSelectedItem();
        if (seleccion != null) {
            if (seleccion instanceof libro_texto) {
                libros.remove(cb_libro.getSelectedIndex());
            } else if (seleccion instanceof libro_referencia) {
                libros.remove(cb_libro.getSelectedIndex());
            } else if (seleccion instanceof libro_ficcion) {
                libros.remove(cb_libro.getSelectedIndex());
            } else if (seleccion instanceof libro_noficcion) {
                libros.remove(cb_libro.getSelectedIndex());
            }
        }
        JOptionPane.showMessageDialog(this, "Libro eliminado correctamente");
    }//GEN-LAST:event_bt_eliminarMouseClicked

    private void cb_librocompraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_librocompraItemStateChanged


        if (evt.getStateChange() == 2) {
            if (cb_librocompra.getSelectedItem() instanceof libro_texto) {
                libro_texto books = (libro_texto) cb_librocompra.getSelectedItem();
                total = books.getPrecio() % 15;
                ta_compra.setText(books.toString());
                ta_transaccion.setText("Sub total: " + books.getPrecio() + "\n\n"
                        + "ISV 15%\n\n"
                        + "Total " + total);
            } else if (cb_librocompra.getSelectedItem() instanceof libro_referencia) {
                libro_referencia books = (libro_referencia) cb_librocompra.getSelectedItem();
                total = books.getPrecio() % 15;
                ta_compra.setText(books.toString());
                ta_transaccion.setText("Sub total: " + books.getPrecio() + "\n\n"
                        + "ISV 15%\n\n"
                        + "Total " + total);
            } else if (cb_librocompra.getSelectedItem() instanceof libro_ficcion) {
                libro_ficcion books = (libro_ficcion) cb_librocompra.getSelectedItem();
                total = books.getPrecio() % 15;
                ta_compra.setText(books.toString());
                ta_transaccion.setText("Sub total: " + books.getPrecio() + "\n\n"
                        + "ISV 15%\n\n"
                        + "Total " + total);
            } else if (cb_librocompra.getSelectedItem() instanceof libro_noficcion) {
                libro_noficcion books = (libro_noficcion) cb_librocompra.getSelectedItem();
                total = books.getPrecio() % 15;
                ta_compra.setText(books.toString());
                ta_transaccion.setText("Sub total: " + books.getPrecio() + "\n\n"
                        + "ISV 15%\n\n"
                        + "Total " + total);
            }

        }
        
    }//GEN-LAST:event_cb_librocompraItemStateChanged

    private void bt_comprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_comprarMouseClicked
        saldo -= total;
        JOptionPane.showMessageDialog(this, "Compra hecha");
        lb_saldo.setText("Saldo de usuario: " + saldo);
    }//GEN-LAST:event_bt_comprarMouseClicked

    private void cb_librodevueleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_librodevueleItemStateChanged

        if (evt.getStateChange() == 2) {
            if (cb_librodevuele.getSelectedItem() instanceof libro_texto) {
                libro_texto books = (libro_texto) cb_librodevuele.getSelectedItem();
                total = books.getPrecio();
                ta_devolver.setText(books.toString());
                ta_reembolzo.setText("Reembolzo: " + books.getPrecio() + "\n\n"
                        + "Total " + total);
            } else if (cb_librodevuele.getSelectedItem() instanceof libro_referencia) {
                libro_referencia books = (libro_referencia) cb_librodevuele.getSelectedItem();
                total = books.getPrecio();
                ta_devolver.setText(books.toString());
                ta_reembolzo.setText("Reembolzo: " + books.getPrecio() + "\n\n"
                        + "Total " + total);
            } else if (cb_librocompra.getSelectedItem() instanceof libro_ficcion) {
                libro_ficcion books = (libro_ficcion) cb_librodevuele.getSelectedItem();
                total = books.getPrecio();
                ta_devolver.setText(books.toString());
                ta_reembolzo.setText("Reembolzo: " + books.getPrecio() + "\n\n"
                        + "Total " + total);
            } else if (cb_librodevuele.getSelectedItem() instanceof libro_noficcion) {
                libro_noficcion books = (libro_noficcion) cb_librodevuele.getSelectedItem();
                total = books.getPrecio();
                ta_devolver.setText(books.toString());
                ta_reembolzo.setText("Reembolzo: " + books.getPrecio() + "\n\n"
                        + "Total " + total);
            }
        }
        
    }//GEN-LAST:event_cb_librodevueleItemStateChanged

    private void bt_devolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_devolverMouseClicked
        saldo+=total;
        JOptionPane.showMessageDialog(this, "Devolucion Hecha");
        lb_saldo.setText("Saldo de usuario: " + saldo);
    }//GEN-LAST:event_bt_devolverMouseClicked

    private void cb_libroeliminarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_libroeliminarItemStateChanged
        String print = "";
        if (evt.getStateChange() == 2) {
            if (cb_libroeliminar.getSelectedItem() instanceof libro_texto) {
                libro_texto books = (libro_texto) cb_libroeliminar.getSelectedItem();
               print+=books;
            } else if (cb_libroeliminar.getSelectedItem() instanceof libro_referencia) {
                libro_referencia books = (libro_referencia) cb_libroeliminar.getSelectedItem();
                print+=books;
            } else if (cb_libroeliminar.getSelectedItem() instanceof libro_ficcion) {
                libro_ficcion books = (libro_ficcion) cb_libroeliminar.getSelectedItem();
                print+=books;
            } else if (cb_libroeliminar.getSelectedItem() instanceof libro_noficcion) {
                libro_noficcion books = (libro_noficcion) cb_libroeliminar.getSelectedItem();
                print+=books;
            }
            ta_eliminar.setText(print);
        }
    }//GEN-LAST:event_cb_libroeliminarItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    String user = "lib123", pswrd = "321lib";
    ArrayList<libro> libros = new ArrayList<>();

    double saldo = 99999;
    double total = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Salir;
    private javax.swing.JButton bt_comprar;
    private javax.swing.JButton bt_devolver;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_loginAdmin;
    private javax.swing.JButton bt_publicar;
    private javax.swing.JButton bt_usuariologin;
    private javax.swing.JComboBox<String> cb_libro;
    private javax.swing.JComboBox<String> cb_librocompra;
    private javax.swing.JComboBox<String> cb_librodevuele;
    private javax.swing.JComboBox<String> cb_libroeliminar;
    private javax.swing.JComboBox<String> cb_listar;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JComboBox<String> cb_tipoFic;
    private javax.swing.JComboBox<String> cb_tipocompra;
    private javax.swing.JComboBox<String> cb_tipodevuelve;
    private javax.swing.JComboBox<String> cb_tipoeliminar;
    private javax.swing.JComboBox<String> cb_tiponofic;
    private javax.swing.JComboBox<String> cb_tiporef;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lb_saldo;
    private javax.swing.JPanel login;
    private javax.swing.JPasswordField pf_adminpswd;
    private javax.swing.JPanel pn_comprar;
    private javax.swing.JPanel pn_devolver;
    private javax.swing.JPanel pn_editar;
    private javax.swing.JPanel pn_eliminar;
    private javax.swing.JPanel pn_librofic;
    private javax.swing.JPanel pn_libronofic;
    private javax.swing.JPanel pn_libroref;
    private javax.swing.JPanel pn_librotexto;
    private javax.swing.JPanel pn_listarlibros;
    private javax.swing.JPanel pn_publicar;
    private javax.swing.JTextArea ta_compra;
    private javax.swing.JTextArea ta_devolver;
    private javax.swing.JTextArea ta_eliminar;
    private javax.swing.JTextArea ta_listar;
    private javax.swing.JTextArea ta_reembolzo;
    private javax.swing.JTextArea ta_transaccion;
    private javax.swing.JTable tb_editar;
    private javax.swing.JTextField tf_adminuser;
    private javax.swing.JTextField tf_autor;
    private javax.swing.JTextField tf_autoreditar;
    private javax.swing.JTextField tf_curso;
    private javax.swing.JTextField tf_facultad;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_precioeditar;
    private javax.swing.JTextField tf_titulo;
    private javax.swing.JTextField tf_tituloeditar;
    private javax.swing.JTabbedPane tp_menuUser;
    private javax.swing.JTabbedPane tp_menuadmin;
    private javax.swing.JTabbedPane tp_modelos;
    // End of variables declaration//GEN-END:variables
}
